/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuaCidadeRouteImport } from './routes/sua-cidade'
import { Route as PeloBrasilRouteImport } from './routes/pelo-brasil'
import { Route as NossaGenteRouteImport } from './routes/nossa-gente'
import { Route as BiografiaRouteImport } from './routes/biografia'
import { Route as IndexRouteImport } from './routes/index'

const SuaCidadeRoute = SuaCidadeRouteImport.update({
  id: '/sua-cidade',
  path: '/sua-cidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PeloBrasilRoute = PeloBrasilRouteImport.update({
  id: '/pelo-brasil',
  path: '/pelo-brasil',
  getParentRoute: () => rootRouteImport,
} as any)
const NossaGenteRoute = NossaGenteRouteImport.update({
  id: '/nossa-gente',
  path: '/nossa-gente',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografiaRoute = BiografiaRouteImport.update({
  id: '/biografia',
  path: '/biografia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biografia': typeof BiografiaRoute
  '/nossa-gente': typeof NossaGenteRoute
  '/pelo-brasil': typeof PeloBrasilRoute
  '/sua-cidade': typeof SuaCidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biografia': typeof BiografiaRoute
  '/nossa-gente': typeof NossaGenteRoute
  '/pelo-brasil': typeof PeloBrasilRoute
  '/sua-cidade': typeof SuaCidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biografia': typeof BiografiaRoute
  '/nossa-gente': typeof NossaGenteRoute
  '/pelo-brasil': typeof PeloBrasilRoute
  '/sua-cidade': typeof SuaCidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biografia'
    | '/nossa-gente'
    | '/pelo-brasil'
    | '/sua-cidade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/biografia' | '/nossa-gente' | '/pelo-brasil' | '/sua-cidade'
  id:
    | '__root__'
    | '/'
    | '/biografia'
    | '/nossa-gente'
    | '/pelo-brasil'
    | '/sua-cidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiografiaRoute: typeof BiografiaRoute
  NossaGenteRoute: typeof NossaGenteRoute
  PeloBrasilRoute: typeof PeloBrasilRoute
  SuaCidadeRoute: typeof SuaCidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sua-cidade': {
      id: '/sua-cidade'
      path: '/sua-cidade'
      fullPath: '/sua-cidade'
      preLoaderRoute: typeof SuaCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelo-brasil': {
      id: '/pelo-brasil'
      path: '/pelo-brasil'
      fullPath: '/pelo-brasil'
      preLoaderRoute: typeof PeloBrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossa-gente': {
      id: '/nossa-gente'
      path: '/nossa-gente'
      fullPath: '/nossa-gente'
      preLoaderRoute: typeof NossaGenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biografia': {
      id: '/biografia'
      path: '/biografia'
      fullPath: '/biografia'
      preLoaderRoute: typeof BiografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiografiaRoute: BiografiaRoute,
  NossaGenteRoute: NossaGenteRoute,
  PeloBrasilRoute: PeloBrasilRoute,
  SuaCidadeRoute: SuaCidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
